version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    expose:
      - "9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/ext/datalake:/data
    env_file:
    - .env
    command: server --console-address ":9001" /data

  dwh:
    container_name: dwh-postgres
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file:
      - dbt.env
    expose:
      - "5432"
    ports:
      - '5430:5432'
    volumes:
      - /mnt/ext/dwh/psql:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8081:8080


networks:
  default:
    name: internal
