version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/ext/datalake:/data
    env_file:
    - .env
    command: server --console-address ":9001" /data
