version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/ext/datalake:/data
    env_file:
    - .env
    command: server --console-address ":9001" /data

  dwh:
    container_name: dwh-postgres
    image: postgres:14.1-alpine
    env_file:
      - dbt.env
    ports:
      - '5432:5432'
    volumes:
      - /mnt/ext/dwh/psql:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080

  # druidpostgres:
  #   container_name: druid-postgres
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - /mnt/ext/dwh/metadata:/var/lib/postgresql/data
  #   env_file:
  #   - druid.env

  # #Need 3.5 or later for container nodes
  # zookeeper:
  #   container_name: zookeeper
  #   image: zookeeper:3.5.10
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     - ZOO_MY_ID=1

  # coordinator:
  #   image: apache/druid:25.0.0
  #   container_name: coordinator
  #   volumes:
  #     - /mnt/ext/dwh/shared:/opt/shared
  #     - /mnt/ext/dwh/coordinator:/opt/druid/var
  #   depends_on:
  #     - zookeeper
  #     - druidpostgres
  #   ports:
  #     - "8081:8081"
  #   command:
  #     - coordinator
  #   env_file:
  #     - druid.env

  # broker:
  #   image: apache/druid:25.0.0
  #   container_name: broker
  #   volumes:
  #     - /mnt/ext/dwh/broker:/opt/druid/var
  #   depends_on:
  #     - zookeeper
  #     - druidpostgres
  #     - coordinator
  #   ports:
  #     - "8082:8082"
  #   command:
  #     - broker
  #   env_file:
  #     - druid.env

  # historical:
  #   image: apache/druid:25.0.0
  #   container_name: historical
  #   volumes:
  #     - /mnt/ext/dwh/shared:/opt/shared
  #     - /mnt/ext/dwh/historical:/opt/druid/var
  #   depends_on:
  #     - zookeeper
  #     - druidpostgres
  #     - coordinator
  #   ports:
  #     - "8083:8083"
  #   command:
  #     - historical
  #   env_file:
  #     - druid.env

  # middlemanager:
  #   image: apache/druid:25.0.0
  #   container_name: middlemanager
  #   volumes:
  #     - /mnt/ext/dwh/shared:/opt/shared
  #     - /mnt/ext/dwh/middlemanager:/opt/druid/var
  #   depends_on:
  #     - zookeeper
  #     - druidpostgres
  #     - coordinator
  #   ports:
  #     - "8091:8091"
  #     - "8100-8105:8100-8105"
  #   command:
  #     - middleManager
  #   env_file:
  #     - druid.env

  # router:
  #   image: apache/druid:25.0.0
  #   container_name: router
  #   volumes:
  #     - /mnt/ext/dwh/router:/opt/druid/var
  #   depends_on:
  #     - zookeeper
  #     - druidpostgres
  #     - coordinator
  #   ports:
  #     - "8888:8888"
  #   command:
  #     - router
  #   env_file:
  #     - druid.env
